In [ ]:
import pandas as pd

In [ ]:
url = "https://gist.githubusercontent.com/netj/8836201/raw/"
df = pd.read_csv(url, on_bad_lines='skip') # skipping any bad lines
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

# New Section

In [ ]:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [ ]:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
df.head(n=10)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

In [ ]:
df.shape

(150, 5)

In [ ]:
df.sum()

sepal.length                                                876.5
sepal.width                                                 458.6
petal.length                                                563.7
petal.width                                                 179.9
variety         SetosaSetosaSetosaSetosaSetosaSetosaSetosaSeto...
dtype: object

In [ ]:
df.sum(numeric_only=True)

sepal.length    876.5
sepal.width     458.6
petal.length    563.7
petal.width     179.9
dtype: float64

In [ ]:
df.mean(numeric_only=True)

sepal.length    5.843333
sepal.width     3.057333
petal.length    3.758000
petal.width     1.199333
dtype: float64

In [ ]:
df.mean()

TypeError: Could not convert ['SetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaSetosaVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVersicolorVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginicaVirginica'] to numeric

In [ ]:
df.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')

In [ ]:
df['sepal.length'].unique()

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.4, 4.8, 4.3, 5.8, 5.7, 5.2, 5.5,
       4.5, 5.3, 7. , 6.4, 6.9, 6.5, 6.3, 6.6, 5.9, 6. , 6.1, 5.6, 6.7,
       6.2, 6.8, 7.1, 7.6, 7.3, 7.2, 7.7, 7.4, 7.9])

In [ ]:
df['sepal.length'].nunique()

35

In [ ]:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html
df.describe()

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
df.describe(include='all', percentiles=[.33, .66])

        sepal.length  sepal.width  petal.length  petal.width variety
count     150.000000   150.000000    150.000000   150.000000     150
unique           NaN          NaN           NaN          NaN       3
top              NaN          NaN           NaN          NaN  Setosa
freq             NaN          NaN           NaN          NaN      50
mean        5.843333     3.057333      3.758000     1.199333     NaN
std         0.828066     0.435866      1.765298     0.762238     NaN
min         4.300000     2.000000      1.000000     0.100000     NaN
33%         5.400000     2.900000      2.087000     0.668000     NaN
50%         5.800000     3.000000      4.350000     1.300000     NaN
66%         6.234000     3.200000      4.834000     1.600000     NaN
max         7.900000     4.400000      6.900000     2.500000     NaN