# Ways to create Pandas DataFrames

We will be using the Iris dataset, which you can find out more about here: https://archive.ics.uci.edu/dataset/53/iris

Documentation:
* https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html
* https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

### Data download and library imports

In [1]:
# Run this cell to download the iris.csv file
!rm -f iris.csv
!wget -q https://dl.dropboxusercontent.com/scl/fi/23hcx4l3b58wqdi1zmdy4/iris.csv?rlkey=it1qrd2p85eeemmpvopvwj0yt&st=waihuz65&dl=0
!mv iris.csv?rlkey=it1qrd2p85eeemmpvopvwj0yt iris.csv

In [2]:
import pandas as pd
import numpy as np

### Using a CSV file

In [3]:
df = pd.read_csv('iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [4]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [5]:
df['SepalLengthCm']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

In [6]:
df['SepalLengthCm'][0]

5.1

In [7]:
df.index

RangeIndex(start=0, stop=150, step=1)

In [8]:
df.set_index('Id')

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           3.0            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
4              4.6           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [9]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [10]:
df=df.set_index('Id')

In [11]:
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           3.0            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
4              4.6           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [12]:
df.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
      dtype='int64', name='Id', length=150)

In [13]:
df['SepalWidthCm'][1]

3.5

In [14]:
df.loc[1]

SepalLengthCm            5.1
SepalWidthCm             3.5
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 1, dtype: object

In [15]:
df.iloc[0]

SepalLengthCm            5.1
SepalWidthCm             3.5
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 1, dtype: object

In [16]:
s = pd.DataFrame({'name':['Gerald','Hansin','Nikil','Shivangi'],'marks':[99,98,97,96]} )

In [17]:
acc_name=s.set_index('name')

In [20]:
acc_name

          marks
name
Gerald       99
Hansin       98
Nikil        97
Shivangi     96

In [21]:
s.iloc[1]

name     Hansin
marks        98
Name: 1, dtype: object

In [22]:
s.loc[1]

name     Hansin
marks        98
Name: 1, dtype: object

In [23]:
acc_name.loc['Hansin']

marks    98
Name: Hansin, dtype: int64

In [24]:
acc_name.iloc[1]

marks    98
Name: Hansin, dtype: int64