# Ways to create Pandas DataFrames

We will be using the Iris dataset, which you can find out more about here: https://archive.ics.uci.edu/dataset/53/iris

Documentation:
* https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html
* https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html
* https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html

### Data download and library imports

In [1]:
# Run this cell to download the iris.csv file
!rm -f iris.csv
!wget -q https://dl.dropboxusercontent.com/scl/fi/23hcx4l3b58wqdi1zmdy4/iris.csv?rlkey=it1qrd2p85eeemmpvopvwj0yt&st=waihuz65&dl=0
!mv iris.csv?rlkey=it1qrd2p85eeemmpvopvwj0yt iris.csv

In [2]:
# Run this cell to download the iris.xlsx file
!rm -f iris.xlsx
!wget -q https://dl.dropboxusercontent.com/scl/fi/5vx67t0y47m60oehyhrqg/iris.xlsx?rlkey=3xrckmx7a1pr1mnjtr9kzn5or&st=uj03criq&dl=0
!mv iris.xlsx?rlkey=3xrckmx7a1pr1mnjtr9kzn5or iris.xlsx

In [3]:
import pandas as pd
import numpy as np

### Using a dictionary

In [ ]:
# The values of the dictionary can be Python lists, Pandas Series, or even 1D NumPy arrays
iris_data = {'SepalLengthCm': [5.1, 4.9, 4.7, 4.6, 5.0],
             'SepalWidthCm': [3.5, 3.0, 3.2, 3.1, 3.6],
             'PetalLengthCm': [1.4, 1.4, 1.3, 1.5, 1.4],
             'PetalWidthCm': [0.2, 0.2, 0.2, 0.2, 0.2],
             'Species': ['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa']}

df = pd.DataFrame(iris_data)
df

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

### Using a 2D List

In [ ]:
data = [[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
        [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
        [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
        [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
        [5.0, 3.6, 1.4, 0.2, 'Iris-setosa']]
# df = pd.DataFrame(data)
df = pd.DataFrame(data, columns=['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species'])
df

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

### Using a NumPy array

In [ ]:
numpy_data = np.array(data) # converting 2D list to a NumPy array
# print(numpy_data)
df = pd.DataFrame(data, columns=['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species'])
df

### Using a CSV file

In [ ]:
df = pd.read_csv('iris.csv')
df

### Using an Excel file

In [ ]:
df = pd.read_excel('iris.xlsx')
df

### Using a URL

In [ ]:
url = "https://gist.githubusercontent.com/netj/8836201/raw/"
df = pd.read_csv(url, on_bad_lines='skip') # skipping any bad lines
df